### ISSUE TITLE
Sketchup Update

### ISSUE THREAD

**Issue by Cesterwo** [rschenk/Sketchup-Glue-Tab-Plugin#1]
I found that sketchup updated their code and that now it seems that this and many other plugins do not work and need updating.

**Comment by rschenk** [comment]
Yes, alas, you are correct. The good news is, though, that someone else has bundled a bunch of functionality, including the glue tab feature, into one totally awesome plugin. Check out: http://www.pumpkinpirate.info/flattery/

**Comment by Cesterwo** [comment]
I am getting this error:

Error Loading File C:/Users/Connor/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/flattery/toolbar.rb
Error: #<SyntaxError: C:/Users/Connor/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/flattery/tabtool.rb:238: syntax error, unexpected ':', expecting keyword_then or ';' or '\n'
C:/Users/Connor/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/flattery/tabtool.rb:276: syntax error, unexpected ':', expecting keyword_then or ';' or '\n'
C:/Users/Connor/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/flattery/tabtool.rb:287: syntax error, unexpected ':', expecting keyword_then or ';' or '\n'
C:/Users/Connor/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/flattery/tabtool.rb:291: syntax error, unexpected keyword_end, expecting end-of-input>
C:/Program Files/SketchUp/SketchUp 2015/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:45:in `require'
C:/Program Files/SketchUp/SketchUp 2015/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:45:in`require'
C:/Users/Connor/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/flattery/toolbar.rb:24:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2015/Tools/extensions.rb:197:in`require'
C:/Program Files/SketchUp/SketchUp 2015/Tools/extensions.rb:197:in `load'
C:/Users/Connor/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/flattery.rb:28:in`register_extension'
C:/Users/Connor/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/flattery.rb:28:in `<top (required)>'

Am I installing it wrong?

**Comment by rschenk** [comment]
Not sure, I didn't write Flattery so you'd have to ask them :-/

**Comment by Cesterwo** [comment]
Cool, I think they have a new version at this link and it seems to be all resolved now.

Thanks for the help man. I really appreciate it.

http://sketchucation.com/pluginstore?pln=Flattery

**Comment by rschenk** [comment]
Great, glad you got it worked out, and thanks for getting in touch!
